apiVersion: v1
kind: Service
metadata:
  name: will-playground
  namespace: dev
spec:
  type: LoadBalancer
  # type: NodePort
  selector:
    app: myapp
  ports:
  - port: 8888
    targetPort: 8888
    # nodePort: 31001